name: Semantic Versioning and Tagging

on:
  pull_request:
    paths:
      - 'modules/**'  # Optional: Only trigger on changes within modules directory

jobs:
  semver-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js (latest)
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'  # Uses the latest stable Node.js version

      - name: Install semantic-release
        run: npm install -g semantic-release

      - name: Configure semantic-release
        run: |
          echo '{"branches": ["main"], "analyzeCommits": ["feat", "fix", "chore", "docs"], "release": {"git": {"changelog": "CHANGELOG.md"}}}' > .semantic-release.json

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Replace with your GitHub token secret name
        run: npx semantic-release

